memory_limit = 512M
upload_max_filesize = 25M
post_max_size = 25M
max_execution_time = 60
date.timezone = America/Mexico_City
display_errors = Off
log_errors = On
error_log = /var/www/html/storage/logs/php.log
opcache.enable = 1
opcache.memory_consumption = 256
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
